### ISSUE TITLE
Uninstalled module disappears from backoffice modules and marketplace section.

### ISSUE THREAD

**Issue by roja45** [PrestaShopCorp/ps_mbo#612]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you uninstall a module from the backoffice, it disappears completely even though the directory is still on the server.  

### Expected behavior

Previously you could find it in the marketplace section to reinstall.

### Steps to reproduce

1) Install a module by uploading a zip
2) Uninstall the module
3) Try to find it in the marketplace to reinstall

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

**Comment by intraordinaire** [comment]
Hello @roja45,

Thanks for your feedback. 

We indeed noted that regression.
Working on it to be able to fix it through the MBO module, or the PrestaShop project quickly.

**Comment by micka-fdz** [comment]
Still an issue here, it's a regression.

Ping @sowbiba 🙏

**Comment by intraordinaire** [comment]
Hello here, @micka-fdz, @roja45,

With the new direction given to the module `ps_mbo`, to be a real Marketplace, it will be difficult for us to find room re-adding this feature.

In the meantime, there are multiple solutions for this : 

- Update to PS 8.x, this is fixed in this version, as they will be shown in the module manager page.
- Upload the module zip. PS will install it, and then, you'll be able to find it in the module manager page.
- Comment or remove this line in the [PS ModuleController.php](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php#L115) will allow you to see them in the module manager page. As there will only be security updates on 1.7.8.x, you should be fine.
- Install modules via command line `php bin/console prestashop module:install/enable/uninstall module_name`.

Hope this will help you and lead you to an acceptable compromise.

**Comment by intraordinaire** [comment]
As discussed yesterday on the Slack OS, we are looking to a better solution to handle this.
Display a tab in the module manager page that will display the list of "Uninstalled modules" seems reasonable for everyone.

In the meantime, please consider using the workarounds specified above, as they are quite easy to implement, and will get you unstuck you faster.

**Comment by intraordinaire** [comment]
Fixed in [v2.4.0](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v2.4.0)
