### ISSUE TITLE
Error in update from Prestashop 1.7.8 to 8.0.4

### ISSUE THREAD

**Issue by ezero0** [PrestaShopCorp/ps_mbo#698]
Hello.

I have a issue with this module when i try to use it in my shop.

System Description:
PHP 8.1
Prestashop 8.0.4
Alma Linux 8
All in a Virtual Machine in my computer (i have been testing the update before i update my shop formally) 

When i activate the ps_mbo module, the module works ok in the back office, i can view the marketplace in the back office but the front-end of my shop crash. 

![image](https://github.com/PrestaShopCorp/ps_mbo/assets/45215336/c8d99d00-b6e8-4b78-a25d-ff2e312b2b70)

I readed some of forums with the error displayed in the screenshot, but nothing works for me. And i readed in the releases page of prestashop that the P8 beta versión have error with this plugin.

The question is: is certainly that the plugin doesnt work at the moment in P8.x or that could be a problem of my shop?

Thank you so much, greetings.

**Comment by intraordinaire** [comment]
Hello @ezero0,

Thanks for the feedback.

Can you tell us the version of the ps_mbo module ?
Is your front-end working well without the module ?

I don't see ps_mbo in the error log, and the module is, normally, not interacting with the front-end.
If your back office working well with the module activated, I don't see why it will break the front end.

If you have not tested it, you may try to completely uninstall the module, and then, install it again.
As it often happens also, it may be due to the cache dir which is not cleared well by Symfony, and then the services are not correctly loaded.

So if you try to delete manually `var/cache/` is it better ?

Hope it will help.

**Comment by ezero0** [comment]
Hello @intraordinaire.

The version of the module is 4.6.1. 
![image](https://github.com/PrestaShopCorp/ps_mbo/assets/45215336/7f967429-aa04-434f-8ee4-e2f212daecf8)

I tried to delete the dev and prod folder in var/cache

I will let you a video with demostration of the error:

https://github.com/PrestaShopCorp/ps_mbo/assets/45215336/9a6b4caf-e85b-46cb-bfb6-dbd308b5b727

Thank you. Best regards.

**Comment by intraordinaire** [comment]
Hello @ezero0 

This is very strange, and we never noticed a behavior like this.

I just tested it on a 8.0.4, and everything is working well on my shop 😔

Updates of PS from 1.7.8 to 8 have also been tested by the core project a lot of times...

Maybe, you can try to uninstall thé module, remove the sources, and try to upload a fresh release from github.
The folder may contains old source files, and, maybe, this is the problem here.

Hope it helps

**Comment by intraordinaire** [comment]
@ezero0 have you tried the proposed solution ?

We also released a v4.7.1 which solve a bunch of issues.

**Comment by intraordinaire** [comment]
As we don't have any news, I close the issue.

Feel free to reopen it if needed, or open another if you find something else.

Thanks !
